services:
  - type: web
    name: sudbotwp
    env: docker
    region: frankfurt
    buildCommand: docker build -t sudbotwp .
    startCommand: node render-server.js
    envVars:
      - key: NODE_VERSION
        value: "20"
    autoDeploy: true
    plan: starter
