services:
  - type: web
    name: sudbot-parser
    env: docker
    region: frankfurt
    buildCommand: |
      docker build -t sudbot-parser .
    startCommand: node render-server.js
    envVars:
      - key: NODE_VERSION
        value: "18"
    autoDeploy: false
    plan: starter
